#!/bin/bash

SIZES=(512 1024 2048 4096)
POLYBENCH=( "2DCONV" "2MM" "3DCONV" "3MM" "ATAX" "BICG" )

benchmark_cpu () {
    for kernel in "${POLYBENCH[@]}"
    do
        for size in "${SIZES[@]}"
        do
            BENCH_NAME=Polybench/${kernel} SIZE=${size} RUNS=3 make run-cpu
        done
    done
}

benchmark_omp_gpu () {
    for kernel in "${POLYBENCH[@]}"
    do
        for size in "${SIZES[@]}"
        do
            BENCH_NAME=Polybench/${kernel} SIZE=${size} RUNS=3 make run-omp-gpu
        done
    done
}

benchmark_omp_cpu () {
    for kernel in "${POLYBENCH[@]}"
    do
        for size in "${SIZES[@]}"
        do
            BENCH_NAME=Polybench/${kernel} SIZE=${size} RUNS=3 make run-omp-cpu
        done
    done
}

llvm_mca () {
    for kernel in "${POLYBENCH[@]}"
    do
        echo "[INFO] Getting LLVM-MCA data from Polybench/${kernel}"
        mkdir -p logs/$kernel
        gcc -S benchmarks/Polybench/${kernel}/src/*.c -I benchmarks/common/ -DRUN_CPU_SEQ -DLLVM_MCA -o /dev/stdout \
            | llvm-mca --iterations=1 > logs/${kernel}/llvm_mca_1.log
        gcc -S benchmarks/Polybench/${kernel}/src/*.c -I benchmarks/common/ -DRUN_CPU_SEQ -DLLVM_MCA -o /dev/stdout \
            | llvm-mca --iterations=128 > logs/${kernel}/llvm_mca_128.log
    done
}

# usage: ./compile test_kernel 2DCONV
test_kernel () {
    kernel="$1"

    mkdir -p bin/test

    echo "[INFO] Compiling in test mode for ${kernel} targetting GPU..." ; \
    gcc -fopenmp -foffload=nvptx-none=-misa=sm_35 -foffload=-lm \
        -I benchmarks/common/ \
        -lm \
        -DRUN_TEST \
        -DRUN_OMP_GPU \
        -o "bin/test/${kernel}_omp_gpu" \
        benchmarks/Polybench/$kernel/src/*.c && \
    echo "[INFO] Launching..." ; \
    bin/test/${kernel}_omp_gpu ; \
    echo "[INFO] Completed"

    echo -e "\n"

    echo "[INFO] Compiling in test mode for ${kernel} targetting CPU..." && \
    gcc -fopenmp -foffload=disable -foffload=-lm \
        -I benchmarks/common/ \
        -lm \
        -DRUN_TEST \
        -DRUN_OMP_CPU \
        -o "bin/test/${kernel}_omp_cpu" \
        benchmarks/Polybench/$kernel/src/*.c && \
    echo "[INFO] Launching..." ; \
    bin/test/${kernel}_omp_cpu ; \
    echo "[INFO] Completed"
}

"$@"
